apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    {{- include "s3proxy.labels" . | nindent 4 }}
data:
  S3PROXY_HOST: {{ .Values.s3.host | quote }}
  S3PROXY_REGION: {{ .Values.s3.region | quote }}
  S3PROXY_IP: "0.0.0.0"
  S3PROXY_PORT: {{ .Values.server.port | quote }}
  S3PROXY_NO_TLS: {{ .Values.server.noTls | quote }}
  S3PROXY_MEMORY_LIMIT_MB: {{ .Values.performance.memoryLimitMb | quote }}
  {{- if index .Values "redis-ha" "enabled" }}
  S3PROXY_REDIS_URL: "redis://{{ .Release.Name }}-redis-ha-haproxy:6379/0"
  {{- else }}
  S3PROXY_REDIS_URL: {{ .Values.externalRedis.url | quote }}
  {{- end }}
  S3PROXY_REDIS_UPLOAD_TTL_HOURS: {{ .Values.externalRedis.uploadTtlHours | quote }}
  S3PROXY_ADMIN_UI: {{ .Values.admin.enabled | quote }}
  S3PROXY_ADMIN_PATH: {{ .Values.admin.path | quote }}
  S3PROXY_LOG_LEVEL: {{ .Values.logLevel | quote }}
