apiVersion: v1
kind: Secret
metadata:
  name: scylla-agent-config
type: Opaque
stringData:
  scylla-manager-agent.yaml: |
    s3:
      access_key_id: minioadmin
      secret_access_key: minioadmin
      provider: Minio
      endpoint: http://s3-gateway.s3proxy:80
