# S3 credentials template for MinIO
# Each database namespace needs its own copy of this secret
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
type: Opaque
stringData:
  ACCESS_KEY_ID: "minioadmin"
  ACCESS_SECRET_KEY: "minioadmin"
