name: Helm Lint

on:
  pull_request:
    paths:
      - 'chart/**'

jobs:
  helm-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1

      - name: Add Helm dependency repositories
        run: |
          helm repo add dandydev https://dandydeveloper.github.io/charts
          helm repo update

      - name: Update Helm dependencies
        run: |
          helm dependency update chart/

      - name: Lint Helm chart
        run: |
          helm lint chart/

      - name: Validate Helm template
        run: |
          helm template s3proxy chart/ --debug > /dev/null
